RGB_MATRIX_EFFECT(dirk)
RGB_MATRIX_EFFECT(solid_reactive_simple_custom)
RGB_MATRIX_EFFECT(solid_reactive_simple_custom_delay)
RGB_MATRIX_EFFECT(solid_reactive_simple_custom_tetris)
RGB_MATRIX_EFFECT(calculator)
RGB_MATRIX_EFFECT(simon_says)

// RGB_MATRIX_EFFECT(held_keys)
// RGB_MATRIX_EFFECT(held_keys_fade_out)

#ifdef RGB_MATRIX_CUSTOM_EFFECT_IMPLS

#include "rgb_effects/dirc.h"
#include "rgb_effects/solid_reactive_simple_custom.h"
#include "rgb_effects/solid_reactive_simple_custom_tetris.h"
#include "rgb_effects/calculator.h"
#include "rgb_effects/simon_says.h"
#include "rgb_effects/held_keys.h"

#endif
